# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1035/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1035/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yanhaotian/ssdk/centerline/BEGPUThinning/2D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yanhaotian/ssdk/centerline/BEGPUThinning/2D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1035/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1035/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yanhaotian/ssdk/centerline/BEGPUThinning/2D/CMakeFiles /home/yanhaotian/ssdk/centerline/BEGPUThinning/2D//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yanhaotian/ssdk/centerline/BEGPUThinning/2D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MySharedLib

# Build rule for target.
MySharedLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MySharedLib
.PHONY : MySharedLib

# fast build rule for target.
MySharedLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/build
.PHONY : MySharedLib/fast

CenterlineExtraction.o: CenterlineExtraction.cpp.o
.PHONY : CenterlineExtraction.o

# target to build an object file
CenterlineExtraction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/CenterlineExtraction.cpp.o
.PHONY : CenterlineExtraction.cpp.o

CenterlineExtraction.i: CenterlineExtraction.cpp.i
.PHONY : CenterlineExtraction.i

# target to preprocess a source file
CenterlineExtraction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/CenterlineExtraction.cpp.i
.PHONY : CenterlineExtraction.cpp.i

CenterlineExtraction.s: CenterlineExtraction.cpp.s
.PHONY : CenterlineExtraction.s

# target to generate assembly for a file
CenterlineExtraction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/CenterlineExtraction.cpp.s
.PHONY : CenterlineExtraction.cpp.s

ExtractSegments.o: ExtractSegments.cpp.o
.PHONY : ExtractSegments.o

# target to build an object file
ExtractSegments.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/ExtractSegments.cpp.o
.PHONY : ExtractSegments.cpp.o

ExtractSegments.i: ExtractSegments.cpp.i
.PHONY : ExtractSegments.i

# target to preprocess a source file
ExtractSegments.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/ExtractSegments.cpp.i
.PHONY : ExtractSegments.cpp.i

ExtractSegments.s: ExtractSegments.cpp.s
.PHONY : ExtractSegments.s

# target to generate assembly for a file
ExtractSegments.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/ExtractSegments.cpp.s
.PHONY : ExtractSegments.cpp.s

LibThinning2D.o: LibThinning2D.cu.o
.PHONY : LibThinning2D.o

# target to build an object file
LibThinning2D.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/LibThinning2D.cu.o
.PHONY : LibThinning2D.cu.o

LibThinning2D.i: LibThinning2D.cu.i
.PHONY : LibThinning2D.i

# target to preprocess a source file
LibThinning2D.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/LibThinning2D.cu.i
.PHONY : LibThinning2D.cu.i

LibThinning2D.s: LibThinning2D.cu.s
.PHONY : LibThinning2D.s

# target to generate assembly for a file
LibThinning2D.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySharedLib.dir/build.make CMakeFiles/MySharedLib.dir/LibThinning2D.cu.s
.PHONY : LibThinning2D.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MySharedLib"
	@echo "... CenterlineExtraction.o"
	@echo "... CenterlineExtraction.i"
	@echo "... CenterlineExtraction.s"
	@echo "... ExtractSegments.o"
	@echo "... ExtractSegments.i"
	@echo "... ExtractSegments.s"
	@echo "... LibThinning2D.o"
	@echo "... LibThinning2D.i"
	@echo "... LibThinning2D.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

